management:
   context-path: /actuator
   security:
             enabled: false
spring:
    datasource:
        url: jdbc:mysql://localhost/rate
        username: root
        password: root
    jpa:
        hibernate:
          ddl-auto: create
